package pe.edu.sistemas.sisasistlab.domain;
// Generated 15/06/2018 04:08:44 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CursoConjunto generated by hbm2java
 */
@Entity
@Table(name = "curso_conjunto", catalog = "modelogeneralfisi")
public class CursoConjunto implements java.io.Serializable {

	private Integer idcursoConjunto;
	private CursoBase cursoBase;
	private String cursocNombre;
	private int cursocCodcomun;
	private Set<CursoPeriodo> cursoPeriodosForCursoPeriodoCursocCodcomun = new HashSet<CursoPeriodo>(0);
	private Set<CursoPeriodo> cursoPeriodosForCursoPeriodoCursocCodcomun_1 = new HashSet<CursoPeriodo>(0);

	public CursoConjunto() {
	}

	public CursoConjunto(CursoBase cursoBase, String cursocNombre, int cursocCodcomun) {
		this.cursoBase = cursoBase;
		this.cursocNombre = cursocNombre;
		this.cursocCodcomun = cursocCodcomun;
	}

	public CursoConjunto(CursoBase cursoBase, String cursocNombre, int cursocCodcomun,
			Set<CursoPeriodo> cursoPeriodosForCursoPeriodoCursocCodcomun,
			Set<CursoPeriodo> cursoPeriodosForCursoPeriodoCursocCodcomun_1) {
		this.cursoBase = cursoBase;
		this.cursocNombre = cursocNombre;
		this.cursocCodcomun = cursocCodcomun;
		this.cursoPeriodosForCursoPeriodoCursocCodcomun = cursoPeriodosForCursoPeriodoCursocCodcomun;
		this.cursoPeriodosForCursoPeriodoCursocCodcomun_1 = cursoPeriodosForCursoPeriodoCursocCodcomun_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDCURSO_CONJUNTO", unique = true, nullable = false)
	public Integer getIdcursoConjunto() {
		return this.idcursoConjunto;
	}

	public void setIdcursoConjunto(Integer idcursoConjunto) {
		this.idcursoConjunto = idcursoConjunto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURSOC_IDCURSO_GENERAL", nullable = false)
	public CursoBase getCursoBase() {
		return this.cursoBase;
	}

	public void setCursoBase(CursoBase cursoBase) {
		this.cursoBase = cursoBase;
	}

	@Column(name = "CURSOC_NOMBRE", nullable = false, length = 100)
	public String getCursocNombre() {
		return this.cursocNombre;
	}

	public void setCursocNombre(String cursocNombre) {
		this.cursocNombre = cursocNombre;
	}

	@Column(name = "CURSOC_CODCOMUN", nullable = false)
	public int getCursocCodcomun() {
		return this.cursocCodcomun;
	}

	public void setCursocCodcomun(int cursocCodcomun) {
		this.cursocCodcomun = cursocCodcomun;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cursoConjuntoByCursoPeriodoCursocCodcomun")
	public Set<CursoPeriodo> getCursoPeriodosForCursoPeriodoCursocCodcomun() {
		return this.cursoPeriodosForCursoPeriodoCursocCodcomun;
	}

	public void setCursoPeriodosForCursoPeriodoCursocCodcomun(
			Set<CursoPeriodo> cursoPeriodosForCursoPeriodoCursocCodcomun) {
		this.cursoPeriodosForCursoPeriodoCursocCodcomun = cursoPeriodosForCursoPeriodoCursocCodcomun;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cursoConjuntoByCursoPeriodoCursocCodcomun")
	public Set<CursoPeriodo> getCursoPeriodosForCursoPeriodoCursocCodcomun_1() {
		return this.cursoPeriodosForCursoPeriodoCursocCodcomun_1;
	}

	public void setCursoPeriodosForCursoPeriodoCursocCodcomun_1(
			Set<CursoPeriodo> cursoPeriodosForCursoPeriodoCursocCodcomun_1) {
		this.cursoPeriodosForCursoPeriodoCursocCodcomun_1 = cursoPeriodosForCursoPeriodoCursocCodcomun_1;
	}

}
