package pe.edu.sistemas.sisasistlab.domain;
// Generated 15/06/2018 04:08:44 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CursoPeriodo generated by hbm2java
 */
@Entity
@Table(name = "curso_periodo", catalog = "modelogeneralfisi")
public class CursoPeriodo implements java.io.Serializable {

	private Integer idcursoPeriodo;
	private CursoConjunto cursoConjuntoByCursoPeriodoCursocCodcomun;
	private CursoConjunto cursoConjuntoByCursoPeriodoCursocCodcomun_1;
	private Periodo periodo;
	private String cursoPeriodoNombre;
	private Set<LaboratorioAsist> laboratorioAsists = new HashSet<LaboratorioAsist>(0);
	private Set<Grupo> grupos = new HashSet<Grupo>(0);
	private Set<Grupo> grupos_1 = new HashSet<Grupo>(0);

	public CursoPeriodo() {
	}

	public CursoPeriodo(CursoConjunto cursoConjuntoByCursoPeriodoCursocCodcomun,
			CursoConjunto cursoConjuntoByCursoPeriodoCursocCodcomun_1, Periodo periodo) {
		this.cursoConjuntoByCursoPeriodoCursocCodcomun = cursoConjuntoByCursoPeriodoCursocCodcomun;
		this.cursoConjuntoByCursoPeriodoCursocCodcomun_1 = cursoConjuntoByCursoPeriodoCursocCodcomun_1;
		this.periodo = periodo;
	}

	public CursoPeriodo(CursoConjunto cursoConjuntoByCursoPeriodoCursocCodcomun,
			CursoConjunto cursoConjuntoByCursoPeriodoCursocCodcomun_1, Periodo periodo, String cursoPeriodoNombre,
			Set<LaboratorioAsist> laboratorioAsists, Set<Grupo> grupos, Set<Grupo> grupos_1) {
		this.cursoConjuntoByCursoPeriodoCursocCodcomun = cursoConjuntoByCursoPeriodoCursocCodcomun;
		this.cursoConjuntoByCursoPeriodoCursocCodcomun_1 = cursoConjuntoByCursoPeriodoCursocCodcomun_1;
		this.periodo = periodo;
		this.cursoPeriodoNombre = cursoPeriodoNombre;
		this.laboratorioAsists = laboratorioAsists;
		this.grupos = grupos;
		this.grupos_1 = grupos_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDCURSO_PERIODO", unique = true, nullable = false)
	public Integer getIdcursoPeriodo() {
		return this.idcursoPeriodo;
	}

	public void setIdcursoPeriodo(Integer idcursoPeriodo) {
		this.idcursoPeriodo = idcursoPeriodo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURSO_PERIODO_CURSOC_CODCOMUN", nullable = false)
	public CursoConjunto getCursoConjuntoByCursoPeriodoCursocCodcomun() {
		return this.cursoConjuntoByCursoPeriodoCursocCodcomun;
	}

	public void setCursoConjuntoByCursoPeriodoCursocCodcomun(CursoConjunto cursoConjuntoByCursoPeriodoCursocCodcomun) {
		this.cursoConjuntoByCursoPeriodoCursocCodcomun = cursoConjuntoByCursoPeriodoCursocCodcomun;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURSO_PERIODO_CURSOC_CODCOMUN", nullable = false, insertable = false, updatable = false)
	public CursoConjunto getCursoConjuntoByCursoPeriodoCursocCodcomun_1() {
		return this.cursoConjuntoByCursoPeriodoCursocCodcomun_1;
	}

	public void setCursoConjuntoByCursoPeriodoCursocCodcomun_1(
			CursoConjunto cursoConjuntoByCursoPeriodoCursocCodcomun_1) {
		this.cursoConjuntoByCursoPeriodoCursocCodcomun_1 = cursoConjuntoByCursoPeriodoCursocCodcomun_1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERIODO_IDPERIODO", nullable = false)
	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@Column(name = "CURSO_PERIODO_NOMBRE", length = 100)
	public String getCursoPeriodoNombre() {
		return this.cursoPeriodoNombre;
	}

	public void setCursoPeriodoNombre(String cursoPeriodoNombre) {
		this.cursoPeriodoNombre = cursoPeriodoNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cursoPeriodo")
	public Set<LaboratorioAsist> getLaboratorioAsists() {
		return this.laboratorioAsists;
	}

	public void setLaboratorioAsists(Set<LaboratorioAsist> laboratorioAsists) {
		this.laboratorioAsists = laboratorioAsists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cursoPeriodo")
	public Set<Grupo> getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Set<Grupo> grupos) {
		this.grupos = grupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cursoPeriodo")
	public Set<Grupo> getGrupos_1() {
		return this.grupos_1;
	}

	public void setGrupos_1(Set<Grupo> grupos_1) {
		this.grupos_1 = grupos_1;
	}

	@Override
	public String toString() {
		return "CursoPeriodo [idcursoPeriodo=" + idcursoPeriodo + ", cursoPeriodoNombre=" + cursoPeriodoNombre + "]";
	}

}
