package pe.edu.sistemas.sisasistlab.domain;
// Generated 13/07/2018 02:11:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LaboratorioAsist generated by hbm2java
 */
@Entity
@Table(name = "laboratorio_asist", catalog = "modelogeneralfisi")
public class LaboratorioAsist implements java.io.Serializable {

	private int idLaboratorioAsist;
	private CursoPeriodo cursoPeriodo;
	private Docente docente;
	private Date laboratorioAsistApertura;
	private Date laboratorioAsistCierre;
	private Date laboratorioAsistFecha;
	private int aulaIdaula;
	private String laboratorioAsistInvolucradoApertura;
	private String laboratorioAsistInvolucradoCierre;

	public LaboratorioAsist() {
	}

	public LaboratorioAsist(int idLaboratorioAsist, CursoPeriodo cursoPeriodo, Docente docente,
			Date laboratorioAsistApertura, Date laboratorioAsistFecha, int aulaIdaula,
			String laboratorioAsistInvolucradoApertura) {
		this.idLaboratorioAsist = idLaboratorioAsist;
		this.cursoPeriodo = cursoPeriodo;
		this.docente = docente;
		this.laboratorioAsistApertura = laboratorioAsistApertura;
		this.laboratorioAsistFecha = laboratorioAsistFecha;
		this.aulaIdaula = aulaIdaula;
		this.laboratorioAsistInvolucradoApertura = laboratorioAsistInvolucradoApertura;
	}

	public LaboratorioAsist(int idLaboratorioAsist, CursoPeriodo cursoPeriodo, Docente docente,
			Date laboratorioAsistApertura, Date laboratorioAsistCierre, Date laboratorioAsistFecha, int aulaIdaula,
			String laboratorioAsistInvolucradoApertura, String laboratorioAsistInvolucradoCierre) {
		this.idLaboratorioAsist = idLaboratorioAsist;
		this.cursoPeriodo = cursoPeriodo;
		this.docente = docente;
		this.laboratorioAsistApertura = laboratorioAsistApertura;
		this.laboratorioAsistCierre = laboratorioAsistCierre;
		this.laboratorioAsistFecha = laboratorioAsistFecha;
		this.aulaIdaula = aulaIdaula;
		this.laboratorioAsistInvolucradoApertura = laboratorioAsistInvolucradoApertura;
		this.laboratorioAsistInvolucradoCierre = laboratorioAsistInvolucradoCierre;
	}

	@Id

	@Column(name = "ID_LABORATORIO_ASIST", unique = true, nullable = false)
	public int getIdLaboratorioAsist() {
		return this.idLaboratorioAsist;
	}

	public void setIdLaboratorioAsist(int idLaboratorioAsist) {
		this.idLaboratorioAsist = idLaboratorioAsist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURSO_IDCURSO", nullable = false)
	public CursoPeriodo getCursoPeriodo() {
		return this.cursoPeriodo;
	}

	public void setCursoPeriodo(CursoPeriodo cursoPeriodo) {
		this.cursoPeriodo = cursoPeriodo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCENTE_ID_DOCENTE", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "LABORATORIO_ASIST_APERTURA", nullable = false, length = 8)
	public Date getLaboratorioAsistApertura() {
		return this.laboratorioAsistApertura;
	}

	public void setLaboratorioAsistApertura(Date laboratorioAsistApertura) {
		this.laboratorioAsistApertura = laboratorioAsistApertura;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "LABORATORIO_ASIST_CIERRE", length = 8)
	public Date getLaboratorioAsistCierre() {
		return this.laboratorioAsistCierre;
	}

	public void setLaboratorioAsistCierre(Date laboratorioAsistCierre) {
		this.laboratorioAsistCierre = laboratorioAsistCierre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LABORATORIO_ASIST_FECHA", nullable = false, length = 10)
	public Date getLaboratorioAsistFecha() {
		return this.laboratorioAsistFecha;
	}

	public void setLaboratorioAsistFecha(Date laboratorioAsistFecha) {
		this.laboratorioAsistFecha = laboratorioAsistFecha;
	}

	@Column(name = "AULA_IDAULA", nullable = false)
	public int getAulaIdaula() {
		return this.aulaIdaula;
	}

	public void setAulaIdaula(int aulaIdaula) {
		this.aulaIdaula = aulaIdaula;
	}

	@Column(name = "LABORATORIO_ASIST_INVOLUCRADO_APERTURA", nullable = false, length = 45)
	public String getLaboratorioAsistInvolucradoApertura() {
		return this.laboratorioAsistInvolucradoApertura;
	}

	public void setLaboratorioAsistInvolucradoApertura(String laboratorioAsistInvolucradoApertura) {
		this.laboratorioAsistInvolucradoApertura = laboratorioAsistInvolucradoApertura;
	}

	@Column(name = "LABORATORIO_ASIST_INVOLUCRADO_CIERRE", length = 45)
	public String getLaboratorioAsistInvolucradoCierre() {
		return this.laboratorioAsistInvolucradoCierre;
	}

	public void setLaboratorioAsistInvolucradoCierre(String laboratorioAsistInvolucradoCierre) {
		this.laboratorioAsistInvolucradoCierre = laboratorioAsistInvolucradoCierre;
	}

}
