package pe.edu.sistemas.sisasistlab.domain;
// Generated 24-ago-2018 0:28:55 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LaboratorioDisp generated by hbm2java
 */
@Entity
@Table(name = "laboratorio_disp", catalog = "modelogeneralfisi")
public class LaboratorioDisp implements java.io.Serializable {

	private int idLaboratorioDisp;
	private Aula aula;
	private byte laboratorioDispEstado;

	public LaboratorioDisp() {
	}

	public LaboratorioDisp(int idLaboratorioDisp, Aula aula, byte laboratorioDispEstado) {
		this.idLaboratorioDisp = idLaboratorioDisp;
		this.aula = aula;
		this.laboratorioDispEstado = laboratorioDispEstado;
	}

	@Id

	@Column(name = "ID_LABORATORIO_DISP", unique = true, nullable = false)
	public int getIdLaboratorioDisp() {
		return this.idLaboratorioDisp;
	}

	public void setIdLaboratorioDisp(int idLaboratorioDisp) {
		this.idLaboratorioDisp = idLaboratorioDisp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AULA_IDAULA", nullable = false)
	public Aula getAula() {
		return this.aula;
	}

	public void setAula(Aula aula) {
		this.aula = aula;
	}

	@Column(name = "LABORATORIO_DISP_ESTADO", nullable = false)
	public byte getLaboratorioDispEstado() {
		return this.laboratorioDispEstado;
	}

	public void setLaboratorioDispEstado(byte laboratorioDispEstado) {
		this.laboratorioDispEstado = laboratorioDispEstado;
	}

}
