package pe.edu.sistemas.sisasistlab.domain;
// Generated 13/07/2018 02:11:42 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LaboratorioDisp generated by hbm2java
 */
@Entity
@Table(name = "laboratorio_disp", catalog = "modelogeneralfisi")
public class LaboratorioDisp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idLaboratorioDisp;
	private Aula aula;
	private String laboratorioDispEstado;

	public LaboratorioDisp() {
	}

	public LaboratorioDisp(int idLaboratorioDisp, Aula aula, String laboratorioDispEstado) {
		this.idLaboratorioDisp = idLaboratorioDisp;
		this.aula = aula;
		this.laboratorioDispEstado = laboratorioDispEstado;
	}

	@Id

	@Column(name = "ID_LABORATORIO_DISP", unique = true, nullable = false)
	public int getIdLaboratorioDisp() {
		return this.idLaboratorioDisp;
	}

	public void setIdLaboratorioDisp(int idLaboratorioDisp) {
		this.idLaboratorioDisp = idLaboratorioDisp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AULA_IDAULA", nullable = false)
	public Aula getAula() {
		return this.aula;
	}

	public void setAula(Aula aula) {
		this.aula = aula;
	}

	@Column(name = "LABORATORIO_DISP_ESTADO", nullable = false)
	public String getLaboratorioDispEstado() {
		return this.laboratorioDispEstado;
	}

	public void setLaboratorioDispEstado(String laboratorioDispEstado) {
		this.laboratorioDispEstado = laboratorioDispEstado;
	}

	@Override
	public String toString() {
		return "LaboratorioDisp [aula=" + aula + ", laboratorioDispEstado=" + laboratorioDispEstado + "]";
	}

	
}
