package pe.edu.sistemas.sisasistlab.domain;
// Generated 24/08/2018 05:00:13 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LaboratorioAsist generated by hbm2java
 */
@Entity
@Table(name = "laboratorio_asist", catalog = "modelogeneralfisi")
public class LaboratorioAsist implements java.io.Serializable {

	private int idLaboratorioAsist;
	private Docente docente;
	private Grupo grupo;
	private LaboratorioDisp laboratorioDisp;
	private Date laboratorioAsistApertura;
	private Date laboratorioAsistCierre;
	private Date laboratorioAsistFecha;
	private String laboratorioAsistInvolucradoApertura;
	private String laboratorioAsistInvolucradoCierre;

	public LaboratorioAsist() {
	}

	public LaboratorioAsist(int idLaboratorioAsist, Docente docente, Grupo grupo, LaboratorioDisp laboratorioDisp,
			Date laboratorioAsistApertura, Date laboratorioAsistFecha, String laboratorioAsistInvolucradoApertura) {
		this.idLaboratorioAsist = idLaboratorioAsist;
		this.docente = docente;
		this.grupo = grupo;
		this.laboratorioDisp = laboratorioDisp;
		this.laboratorioAsistApertura = laboratorioAsistApertura;
		this.laboratorioAsistFecha = laboratorioAsistFecha;
		this.laboratorioAsistInvolucradoApertura = laboratorioAsistInvolucradoApertura;
	}

	public LaboratorioAsist(int idLaboratorioAsist, Docente docente, Grupo grupo, LaboratorioDisp laboratorioDisp,
			Date laboratorioAsistApertura, Date laboratorioAsistCierre, Date laboratorioAsistFecha,
			String laboratorioAsistInvolucradoApertura, String laboratorioAsistInvolucradoCierre) {
		this.idLaboratorioAsist = idLaboratorioAsist;
		this.docente = docente;
		this.grupo = grupo;
		this.laboratorioDisp = laboratorioDisp;
		this.laboratorioAsistApertura = laboratorioAsistApertura;
		this.laboratorioAsistCierre = laboratorioAsistCierre;
		this.laboratorioAsistFecha = laboratorioAsistFecha;
		this.laboratorioAsistInvolucradoApertura = laboratorioAsistInvolucradoApertura;
		this.laboratorioAsistInvolucradoCierre = laboratorioAsistInvolucradoCierre;
	}

	@Id

	@Column(name = "ID_LABORATORIO_ASIST", unique = true, nullable = false)
	public int getIdLaboratorioAsist() {
		return this.idLaboratorioAsist;
	}

	public void setIdLaboratorioAsist(int idLaboratorioAsist) {
		this.idLaboratorioAsist = idLaboratorioAsist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCENTE_ID_DOCENTE", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRUPO_IDGRUPO", nullable = false)
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LABORATORIODISP_ID", nullable = false)
	public LaboratorioDisp getLaboratorioDisp() {
		return this.laboratorioDisp;
	}

	public void setLaboratorioDisp(LaboratorioDisp laboratorioDisp) {
		this.laboratorioDisp = laboratorioDisp;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "LABORATORIO_ASIST_APERTURA", nullable = false, length = 8)
	public Date getLaboratorioAsistApertura() {
		return this.laboratorioAsistApertura;
	}

	public void setLaboratorioAsistApertura(Date laboratorioAsistApertura) {
		this.laboratorioAsistApertura = laboratorioAsistApertura;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "LABORATORIO_ASIST_CIERRE", length = 8)
	public Date getLaboratorioAsistCierre() {
		return this.laboratorioAsistCierre;
	}

	public void setLaboratorioAsistCierre(Date laboratorioAsistCierre) {
		this.laboratorioAsistCierre = laboratorioAsistCierre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LABORATORIO_ASIST_FECHA", nullable = false, length = 10)
	public Date getLaboratorioAsistFecha() {
		return this.laboratorioAsistFecha;
	}

	public void setLaboratorioAsistFecha(Date laboratorioAsistFecha) {
		this.laboratorioAsistFecha = laboratorioAsistFecha;
	}

	@Column(name = "LABORATORIO_ASIST_INVOLUCRADO_APERTURA", nullable = false, length = 45)
	public String getLaboratorioAsistInvolucradoApertura() {
		return this.laboratorioAsistInvolucradoApertura;
	}

	public void setLaboratorioAsistInvolucradoApertura(String laboratorioAsistInvolucradoApertura) {
		this.laboratorioAsistInvolucradoApertura = laboratorioAsistInvolucradoApertura;
	}

	@Column(name = "LABORATORIO_ASIST_INVOLUCRADO_CIERRE", length = 45)
	public String getLaboratorioAsistInvolucradoCierre() {
		return this.laboratorioAsistInvolucradoCierre;
	}

	public void setLaboratorioAsistInvolucradoCierre(String laboratorioAsistInvolucradoCierre) {
		this.laboratorioAsistInvolucradoCierre = laboratorioAsistInvolucradoCierre;
	}

}
