package pe.edu.sistemas.sisasistlab.domain;
// Generated 24/08/2018 05:00:13 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LaboratorioDisp generated by hbm2java
 */
@Entity
@Table(name = "laboratorio_disp", catalog = "modelogeneralfisi")
public class LaboratorioDisp implements java.io.Serializable {

	private int idLaboratorioDisp;
	private Aula aula;
	private String laboratorioDispEstado;
	private Set<LaboratorioAsist> laboratorioAsists = new HashSet<LaboratorioAsist>(0);

	public LaboratorioDisp() {
	}

	public LaboratorioDisp(int idLaboratorioDisp, Aula aula) {
		this.idLaboratorioDisp = idLaboratorioDisp;
		this.aula = aula;
	}

	public LaboratorioDisp(int idLaboratorioDisp, Aula aula, String laboratorioDispEstado,
			Set<LaboratorioAsist> laboratorioAsists) {
		this.idLaboratorioDisp = idLaboratorioDisp;
		this.aula = aula;
		this.laboratorioDispEstado = laboratorioDispEstado;
		this.laboratorioAsists = laboratorioAsists;
	}

	@Id

	@Column(name = "ID_LABORATORIO_DISP", unique = true, nullable = false)
	public int getIdLaboratorioDisp() {
		return this.idLaboratorioDisp;
	}

	public void setIdLaboratorioDisp(int idLaboratorioDisp) {
		this.idLaboratorioDisp = idLaboratorioDisp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AULA_IDAULA", nullable = false)
	public Aula getAula() {
		return this.aula;
	}

	public void setAula(Aula aula) {
		this.aula = aula;
	}

	@Column(name = "LABORATORIO_DISP_ESTADO", length = 1)
	public String getLaboratorioDispEstado() {
		return this.laboratorioDispEstado;
	}

	public void setLaboratorioDispEstado(String laboratorioDispEstado) {
		this.laboratorioDispEstado = laboratorioDispEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "laboratorioDisp")
	public Set<LaboratorioAsist> getLaboratorioAsists() {
		return this.laboratorioAsists;
	}

	public void setLaboratorioAsists(Set<LaboratorioAsist> laboratorioAsists) {
		this.laboratorioAsists = laboratorioAsists;
	}

}
